version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app


# dockerize -wait tcp://db:5432 -timeout 40s 